### ISSUE TITLE
What can I check ?

### ISSUE THREAD

**Issue by howi42** [QuentinCG/Milight-Wifi-Bridge-3.0-Python-Library#6]
I am using an Ibox2, it works fine from the app.

Through a PC I get this 👍 
`
pi@raspberrypi:~ $ python3 MilightWifiBridge.py --ip 10.0.0.50 --zone 1 --turnOff
Ip: 10.0.0.50
Zone: 1
Timeout: 5.0
Port: 5987
DEBUG:root:UDP connection initialized with ip 10.0.0.50 and port 5987
DEBUG:root:Milight bridge connection initialized with ip 10.0.0.50:5987 : True
DEBUG:root:Sending frame 'b'200000001602623ad5eda301ae082d466141a7f6dcafd3e600001e'' to 10.0.0.50:5987
DEBUG:root:Start session (mac address: f0:fe:6b:72:b8:fa, session ID 1: 9, session ID 2: 0)
DEBUG:root:Sending request with command 'b'310000080402000000'' with session ID 1 '9', session ID 2 '0' and sequence number '1'
DEBUG:root:Received valid response for previously sent request
DEBUG:root:Turn off zone 1: True
Turn off zone 1: True

`
From what I can see, that looks good.

But no result !

Is there more I can check ?

**Comment by QuentinCG** [comment]
Your output means the PC can communicate with the bridge.

I'm pretty sure the "link" is not the same between your app and the pc... I got this issue on some bridge....
Please try to also link the bridge with your pc (light on the bulbs max 3sec before calling this command): `python3 MilightWifiBridge.py --ip 10.0.0.50 --zone 1 --link`

**Comment by howi42** [comment]
Thanks a lot, I forgot this.
